#
# This compose file spins up a Redis + Postgres container for development
#

volumes:
  redis-data:
  pg-data:

services:
  redis:
    image: redis:6-alpine
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15-alpine
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user
    volumes:
      - pg-data:/var/lib/postgresql/data
